# ---------------------------------------------------------------
#   Site Information And Theme Configuration Settings
#   language: zh-CN
# ---------------------------------------------------------------
## /开头为hexo/public,  ./为主题source
## menu 菜单，hexo/public
menu:
- page: 首页
  url: /
  icon:
- page: 教程
  url: /categories/教程/
  icon:
- page: 随笔
  url: /categories/随笔/
  icon:
- page: 学习记录
  url: /categories/学习记录/
  icon:
- page: 时间轴
  url: /archives/
  icon:

## favicon 标签页缩略图
favicon: /favicon.ico

## Feed rss
rss: /atom.xml

## Carousel 广告栏
carousel:
  img: './img/head-img.jpg'
  url: '/'

# 各个小工具的设置

## widgets
widgets:
  - notification
  - category
  - search
  - tagcloud
  - social
  - archive
  - friends


## 搜索
jsonContent:
  searchLocal: true
  searchGoogle: true
  posts:
    title: true
    text: true
    content: true
    categories: true
    tags: true

## 网站公告设置
notification: |-
            <p>
                这个博客是用来记录我在学习过程中的经验收获和错误总结，为了方便自己以后查询也方便其他访客学习交流。<br/>
            </p>

## 社交设置
social:
 - name: Github
   icon: git
   href: //github.com/TonyLoveCoding
 - name: 邮箱：765534395@qq.com
   icon: envelope-o
   href: mailto:765534395@qq.com
 - name: QQ：765534395
   icon: qq
   href: /
 - name: 微信：a13421865213
   icon: weixin
   href: /
 - name: QQ群
   icon: users
   href: /
 - name: RSS
   icon: feed
   href: /atom.xml

## 文章分类设置
cate_config:
   show_count: true
   show_current: true

## 文章归档设置
arch_config:
   type: 'monthly'
   format: 'YYYY年MM月'
   show_count: true
   order: -1

## 标签云设置
tagcloud:
  tag3d: false
  textColour: '#444'
  outlineMethod: 'block'
  outlineColour: '#FFDAB9'
  interval: 30
  freezeActive: true
  frontSelect: true
  reverse: true
  wheelZoom: false

## 友链设置
links:
  - Hexo官网: https://hexo.io/zh-cn/
  - 博客主题: https://github.com/shenliyang/hexo-theme-snippet


# 主题自定义个性化配置

## 网站宣传语
branding: Study hard, play hard

## 设置banner背景图片
banner:
    img: ./img/banner.jpg

## 首页列表底部面板
homePanel: true

## 缩略图自定义随机图片
defaultImgs:
  -

## 截取文章首页描述字数
excerptLength: 120

## 是否开启文章目录
toc: true

## 代码高亮配置
highlightTheme:

## bootstrap配置
bootstrap:

## ICON配置
fontAwesome:

## 文章过期提醒功能
warning:
  days: 300
  text: '本文于%d天之前发表，文中内容可能已经过时。'

## 文章内声明
declaration:
  enable: true
  title: '转载声明'
  tip: |-
      商业转载请联系作者获得授权,非商业转载请注明出处 © <a href="www.tonyyao.top" target="_blank">Tony Yao个人博客</a>

## 文章打赏
reward:
  alipay: ''
  wepay: ''
  tip: 赞赏是不耍流氓的鼓励

## 主题评论

## Valine评论
valine:
   enable: true
   appId: xOKV9J4UeQAtVkvnJC7Kq2Jn-gzGzoHsz
   appKey: erIpQac4azoCmgfBB7Dl9maa
   placeholder: 说点什么吧
   notify: false
   verify: true
   avatar: mm
   meta: nick,mail
   pageSize: 10

### 畅言评论(需要ICP备案)
changyan:
  enable: false
  appid:
  conf:

### 来必力
livere:
  enable: false
  livere_uid: MTAyMC8zMzA1MS85NjEz

## Gitalk评论
gitalk:
   enable: false
   clientID:
   clientSecret:
   repo:
   owner:
   admin:
   perPage:
   distractionFreeMode: true

### Disqus评论
disqus:
  enable: false
  shortname: snippet
  count: false

### gitment评论(长期不更新，不建议使用)
gitment:
  enable: false
  owner:
  repo:
  client_id:
  client_secret:
  perPage: 10

### 友言评论(服务不稳定)
uyan:
  enable: false
  uyan_id: 1966422


## 网站访客统计
visit_counter:
   site: false
   page: false

## 网站访问统计分析

### 网盟CNZZ统计
cnzz_analytics: 1263868967

### 百度统计
baidu_analytics:

### 谷歌统计
google_analytics:

### 腾讯分析
tencent_analytics:

### 百度站点认证
baidu_site_verification:

### 百度自动推送
baidu_push: false

#网站主题配置
since: 2019
robot: 'all' ### 控制搜索引擎的抓取和索引编制行为，默认为all
version: 1.2.3
